pull_request_rules:
  - name: Automatic merge during office hours + hotfix support
    description: Merge when PR passes all branch protection during office hours,
      except for hotfix
    conditions:
      - or:
          - schedule = Mon-Fri 09:00-17:00[America/Los_Angeles]
          - label = hotfix
    actions:
      merge:
  - name: Make sure PR are almost up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions:
      - "#commits-behind >= 10"
    actions:
      update:
  - name: Make sure PR are up to date before merging with rebase
    description: This automatically rebases PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions: []
    actions:
      rebase:
