name: Auto-approve Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    name: Auto-approve safe Dependabot updates
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Get Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine approval eligibility
        id: should-approve
        run: |
          echo "Checking approval eligibility..."
          echo "Update type: ${{ steps.metadata.outputs.update-type }}"
          echo "Dependency type: ${{ steps.metadata.outputs.dependency-type }}"
          
          # Auto-approve patch updates and development dependencies
          if [[ "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-patch" ]] || \
             [[ "${{ steps.metadata.outputs.dependency-type }}" == "direct:development" ]] || \
             [[ "${{ contains(github.event.pull_request.labels.*.name, 'automerge') }}" == "true" ]]; then
            echo "✅ Eligible for auto-approval"
            echo "should-approve=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Requires manual approval"
            echo "should-approve=false" >> $GITHUB_OUTPUT
          fi

      - name: Auto-approve PR
        if: steps.should-approve.outputs.should-approve == 'true'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add approval comment
        if: steps.should-approve.outputs.should-approve == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `✅ **Auto-approved**
              
              This Dependabot PR has been automatically approved because it meets our safety criteria:
              - Update type: \`${{ steps.metadata.outputs.update-type }}\`
              - Dependency type: \`${{ steps.metadata.outputs.dependency-type }}\`
              
              The PR will be auto-merged once all CI checks pass (if eligible).`
            });