name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  VITE_PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  VITE_PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [deploy-trigger]

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          VITE_PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}